FrontEnd/Controllers/CategoryController.cs
using FrontEnd.Helpers.Interfaces;
using FrontEnd.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FrontEnd.Controllers
{
    public class CategoryController : Controller
    {

        ICategoryHelper _categoryHelper;

        public CategoryController(ICategoryHelper categoryHelper)
        {
            _categoryHelper = categoryHelper;
        }

        // GET: CategoryController
        public ActionResult Index()
        {
            return View(_categoryHelper.GetCategories());
        }

        // GET: CategoryController/Details/5
        public ActionResult Details(int id)
        {
            var result = _categoryHelper.GetCategory(id);
            return View(result);
        }

        // GET: CategoryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoryViewModel category)
        {
            try
            {
                _categoryHelper.Add(category);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CategoryController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_categoryHelper.GetCategory(id));
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CategoryViewModel category)
        {
            try
            {
                _categoryHelper.Update(category);
                return RedirectToAction("Details", new { id = category.CategoriaId });
            }
            catch
            {
                return View();
            }
        }

        // GET: CategoryController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_categoryHelper.GetCategory(id));
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(CategoryViewModel category)
        {
            try
            {
                _categoryHelper.Delete(category.CategoriaId);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

FrontEnd/Controllers/FacturaController.cs
using FrontEnd.Helpers.Interfaces;
using FrontEnd.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FrontEnd.Controllers
{
    public class FacturaController : Controller
    {
        const string SessionKey = "Carrito";
        IFacturaHelper _facturaHelper;
        IUsuarioHelper _usuarioHelper;

        private List<CarritoViewModel> GetCarrito()
        {
            var carritoJson = HttpContext.Session.GetString(SessionKey);
            return string.IsNullOrEmpty(carritoJson) ? new List<CarritoViewModel>() : JsonConvert.DeserializeObject<List<CarritoViewModel>>(carritoJson);
        }


        public FacturaController(IFacturaHelper facturaHelper, IUsuarioHelper usuarioHelper)
        {
            _facturaHelper = facturaHelper;
            _usuarioHelper = usuarioHelper;
        }

        // GET: FacturaController
        public ActionResult Index()
        {
            var data = _facturaHelper.GetFacturas();
            return View(data);
        }

        public IActionResult GenerarFactura()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Usuario");
            }

            var carrito = GetCarrito();
            if (!carrito.Any())
                return RedirectToAction("Carrito", "Carrito");

            var model = new FacturaViewModel
            {
                Fecha = DateTime.Now,
                Estado = "Pendiente",
                MetodoPago = "",
                Subtotal = carrito.Sum(p => p.Cantidad * p.Precio),
                DetalleFacturas = carrito.Select(c => new DetalleFacturaViewModel
                {
                    ProductoId = c.Id,
                    Cantidad = c.Cantidad,
                    PrecioUnitario = c.Precio,
                    Subtotal = c.Cantidad * c.Precio,
                }).ToList(),
                Descuento = carrito.Sum(p => p.Descuento),
                Total = carrito.Sum(p => p.Cantidad * p.Precio) - carrito.Sum(p => p.Descuento)
            };

            return View("FormularioFactura", model);
        }

        [HttpPost]
        public IActionResult ConfirmarCompra(FacturaViewModel factura)
        {
            if (User.Identity.IsAuthenticated)
            {
                var usuarioIdClaim = User.Identity.Name;
                var usuario = _usuarioHelper.GetUsuarioByCorreo(usuarioIdClaim);
                if (usuarioIdClaim != null)
                {
                    factura.UsuarioId = usuario.UsuarioID;
                }
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }

            _facturaHelper.Add(factura);

            // Limpiar carrito tras compra
            HttpContext.Session.Remove(SessionKey);

            return RedirectToAction("Confirmacion");
        }

        public IActionResult Confirmacion()
        {
            return View(); 
        }


        // GET: FacturaController/Details/5
        public ActionResult Details(int id)
        {
            var result = _facturaHelper.GetFactura(id);
            return View(result);
        }

        // GET: FacturaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FacturaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FacturaViewModel factura)
        {
            try
            {
                _facturaHelper.Add(factura);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FacturaController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_facturaHelper.GetFactura(id));
        }

        // POST: FacturaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FacturaViewModel factura)
        {
            try
            {
                _facturaHelper.Update(factura);
                return RedirectToAction("Details", new { id = factura.FacturaId });
            }
            catch
            {
                return View();
            }
        }

        // GET: FacturaController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_facturaHelper.GetFactura(id));
        }

        // POST: FacturaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(FacturaViewModel factura)
        {
            try
            {
                _facturaHelper.Delete(factura.FacturaId);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

FrontEnd/Controllers/ProductoController.cs
using FrontEnd.Helpers.Implementations;
using FrontEnd.Helpers.Interfaces;
using FrontEnd.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FrontEnd.Controllers
{
    public class ProductoController : Controller
    {

        IProductoHelper _productoHelper;
        ICategoryHelper _categoryHelper;

        public ProductoController(IProductoHelper productoHelper, ICategoryHelper categoryHelper)
        {
            _productoHelper = productoHelper;
            _categoryHelper = categoryHelper;
        }

        // GET: ProductoController
        public ActionResult Index()
        {
            ProductoViewModel producto = new ProductoViewModel();
            var test = _categoryHelper.GetCategories();
            producto.Categorias = test;


            return View(_productoHelper.GetProductos());
           // return View(_productoHelper.GetProductos());
        }

        // GET: ProductoController/Details/5
        public ActionResult Details(int id)
        {
            ProductoViewModel producto = _productoHelper.GetProducto(id);
            producto.CategoriaNombre = _categoryHelper.GetCategory(producto.CategoriaId).Nombre;

            return View(producto);
        }

        // GET: ProductoController/Create
        public ActionResult Create()
        {
            ProductoViewModel producto = new ProductoViewModel();
            //producto.Categorias = _categoryHelper.GetCategories();
            var cat = _categoryHelper.GetCategories();
            producto.Categorias= cat;

            return View(producto);
        }

        // POST: ProductoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductoViewModel producto)
        {
            try
            {
                producto.ProductoId = null;
                _productoHelper.Add(producto);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductoController/Edit/5
        public ActionResult Edit(int id)
        {
            ProductoViewModel product = _productoHelper.GetProducto(id);
            product.Categorias = _categoryHelper.GetCategories();
            return View(product);
        }

        // POST: ProductoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductoViewModel producto)
        {
            try
            {
                _productoHelper.Update(producto);
                return RedirectToAction("Details", new { id = producto.ProductoId });
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductoController/Delete/5
        public ActionResult Delete(int id)
        {
            ProductoViewModel product = _productoHelper.GetProducto(id);
            product.CategoriaNombre = _categoryHelper
                                    .GetCategory(product.CategoriaId)
                                    .Nombre;

            return View(product);
        }

        // POST: ProductoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(ProductoViewModel producto)
        {
            try
            {
                _productoHelper.Delete(producto.ProductoId ?? 0);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


    }
}

FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FrontEnd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FrontEnd.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Views/CSS/Principal.css" asp-append-version="true" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">

</head>
<body>
    

    @{
        @using Microsoft.AspNetCore.Http
        @inject IHttpContextAccessor HttpContextAccessor
        @using System.Security.Claims

        var user = HttpContextAccessor.HttpContext?.User;
        var isAuthenticated = user?.Identity?.IsAuthenticated ?? false;
        var isAdmin = user.IsInRole("Administrador");
    }


    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom shadow-sm">
            <div class="container-lg">
                <a class="navbar-brand fw-bold text-primary" asp-area="" asp-controller="Home" asp-action="Index">ELECTRONEW</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar" aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="mainNavbar">
                    <ul class="navbar-nav ms-auto gap-3">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Producto" asp-action="Index">Productos</a>
                        </li>
                        @if(isAdmin)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Category" asp-action="Index">Categorías</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Usuario" asp-action="ListadoDeUsuarios">Usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Factura" asp-action="Index">Facturas</a>
                            </li>
                        }
                    </ul>

                    

                        

                    <ul class="navbar-nav ms-auto gap-3">
                        @if (isAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="btn btn-outline-danger" asp-controller="Usuario" asp-action="Logout">Cerrar sesión</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="btn btn-outline-primary" asp-controller="Usuario" asp-action="Login">Iniciar sesión</a>
                            </li>
                        }
                        <li class="nav-item" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
                            <i class="bi bi-cart"></i>
                            Carrito
                        </li>
                    </ul>
                    

                    

                </div>
            </div>
        </nav>
    </header>

    <div class="container-lg my-4">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top bg-light text-muted py-3 mt-auto">
        <div class="container-lg d-flex justify-content-between align-items-center flex-wrap">
            <span>&copy; 2025 - FrontEnd</span>
            <a class="text-muted" asp-controller="Home" asp-action="Privacy">Política de Privacidad</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

<div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title">Carrito</h5>
        <button type="button" class="btn-close btn-close-Black" data-bs-dismiss="offcanvas"></button>
    </div>
    <div class="offcanvas-body" id="carritoContenido">
        @await Component.InvokeAsync("Carrito")


    </div>
</div>
</html>